# Continuous Integration config
# travis-ci.org
#
# see http://about.travis-ci.org/docs/user/build-configuration/
#

language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "pypy"

# command to install dependencies
install:
  - "pip install cherrypy --use-mirrors"
  - "if [[ $TRAVIS_PYTHON_VERSION = 2.6 ]]; then pip install unittest2 --use-mirrors; fi"

# prepare test run; test local install
before_script:
  - python setup.py -q install

# command to run tests
script: nosetests

branches:
  # whitelist
  only:
    - master
    - devel

# notifications:
# email:
#   recipients:
#     - tilman.boerner@gmx.de
#   on_success: change  # [always|never|change] # default: change
#   on_failure: always  # [always|never|change] # default: always
